name: Auto-tag release

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  auto-tag:
    uses: tylerbutler/actions/.github/workflows/auto-tag.yml@231702af96884c81aba2e69d60ed8ed7d23da69b # ratchet:tylerbutler/actions/.github/workflows/auto-tag.yml@main
    with:
      create-release: true
    secrets:
      app-id: ${{ secrets.RELEASE_APP_ID }}
      app-private-key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
